---
apiVersion: v1
kind: Namespace
metadata:
  name: gateway-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee
  namespace: gateway-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coffee
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: coffee
    spec:
      containers:
        - name: coffee
          image: 'nginxdemos/nginx-hello:plain-text'
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: coffee-service
  namespace: gateway-test
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: coffee
